### ISSUE TITLE
Some entries fail to render

### ISSUE THREAD

**Issue by aehlke** [aehlke/epywing#1]
In several dicts (both free & commercial), on Linux.

Traceback (most recent call last):
File "/home/co/c/manabi-dict/src/manabidict/epwingprotocol.py", line 51, in run
self._render(self.render_entries(self.resource))
File "/home/co/c/manabi-dict/src/manabidict/epwingprotocol.py", line 65, in _render
for chunk in renderer:
File "/home/co/c/manabi-dict/src/manabidict/epwingprotocol.py", line 129, in render_entries
for chunk in entry.text_iterator():
File "/usr/local/lib/python2.6/dist-packages/epywing-0.1-py2.6.egg/epywing/bookfilter.py", line 98, in decorator
for ret in func(self, _args, *_kwargs):
File "/usr/local/lib/python2.6/dist-packages/epywing-0.1-py2.6.egg/epywing/epwingentry.py", line 137, in text_iterator
for chunk in self.parent._get_content_iterator(self.subbook, self._text_location, None, eb_read_text):
File "/usr/local/lib/python2.6/dist-packages/epywing-0.1-py2.6.egg/epywing/epwing.py", line 264, in _get_content_iterator
yield clean_data(data)
File "/usr/local/lib/python2.6/dist-packages/epywing-0.1-py2.6.egg/epywing/epwing.py", line 207, in clean_data
data = self.gaiji_handler.replace_all_gaiji_tags(data)
File "/usr/local/lib/python2.6/dist-packages/epywing-0.1-py2.6.egg/epywing/gaiji.py", line 53, in replace_all_gaiji_tags
return self.GAIJI_REGEX.sub(_replace_gaiji_tag, html)
File "/usr/local/lib/python2.6/dist-packages/epywing-0.1-py2.6.egg/epywing/gaiji.py", line 51, in _replace_gaiji_tag
return self.gaiji(width_code, index)
File "/usr/local/lib/python2.6/dist-packages/epywing-0.1-py2.6.egg/epywing/bookfilter.py", line 70, in tag_decorator
return func(self, width_code, index)
File "/usr/local/lib/python2.6/dist-packages/epywing-0.1-py2.6.egg/epywing/gaiji.py", line 42, in gaiji
gif_data = self.gif(width, index, font_size)
File "/usr/local/lib/python2.6/dist-packages/epywing-0.1-py2.6.egg/epywing/gaiji.py", line 86, in gif
width = eb_wide_font_width(book)
eb.EBError: (44, 'no current font')

**Comment by aehlke** [comment]
Entry "でにーる" for example: http://www.wadoku.de:81/wadoku_ebz.zip
